### ISSUE TITLE
Epoch 1.0 testing issues on Bullet Buffet (10/24/17)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#945] opened 2017-10-24 09:55 UTC
**Here are some issues I encountered playing tonight: Bullet Buffet on Malden, using latest build as of 12:15 AM CST 10/24/17**

- [ ] CreateVehicle #0 Kick from selecting a weapon from your favorites bar

- [x] Geiger counter goes in the GPS slot, as intended?
 
- [x] Geiger counter appears to give warning beeps even when you run out of energy even though the HUD of the counter does not update
 
- [x] Bundle of Pipes object not setup to salvage with sledge? 
 https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_Pipes_large_F.jpg
 or https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_Pipes_small_F.jpg I think it was the small variant I tested on
 
- [x] Geiger counter goes in the GPS slot, as intended? (Yes)
 
- [x] Geiger counter appears to give warning beeps even when you run out of energy
 
- [x] Bundle of Pipes object not setup to salvage with sledge? 
 https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_Pipes_large_F.jpg
or https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_Pipes_small_F.jpg I think it was the small variant I tested on
 
- [x] The blue garbage cans on Malden were not lootable
 
- [ ] Summer Clothes (Red) was not wearable by a male character 
 ![20171024015523_1](https://user-images.githubusercontent.com/4204940/31936042-a9b934d6-b86d-11e7-9aed-0a96f96c45ee.jpg)
 
- [x] Underwater loot from shipwrecks are not available on Malden
 
- [x] Traps (wooden spike, metal spike traps)that are placed seem to not be disposing upon server restart, making them "persistent" and perhaps invisible upon server restart.  Further testing required
 
**Feedback / Suggestions**

Add a hint (tutorial text) to the epicenter (ore vein) and satellite to indicate how a player can harvest materials from it.  Since a sledgehammer / maul is required- this could be confusing for new players

Is it possible to find a pistol in a toilet? If not- then please add it :) ode to 7D2D

Radiation medicine works, but with the ultra fast text scrolling, you don't even see the effect in the list. Just an observation- if you have your debug menu open you see the effects but when a medical item is used and has multiple effects you can't see all of them.

Warning beeps for the geiger counter are slightly too loud (saw that you guys know this, just my two cents)

Many towns are irradiated now, perhaps to a fault.  On Malden - at least 4 large towns were irradiated, only leaving a few that weren't.  We did not find any radiation medicine- so this is a bit much for players who need to loot. Maybe limit to one or two towns or reduce the area that is irradiated? Not sure what exactly is needed to balance it out.

Can markers be updated (cargo, epicenter, satellite) be updated when they are looted / destroyed?  Not sure how Arma 3 handles this- does a check every X minutes or so?
**One issue**
 - [x] Loot positions for this house are slightly off
![20171025002221_1](https://user-images.githubusercontent.com/4204940/31990673-ff1831e6-b932-11e7-94d5-2814054f956a.jpg)
![20171025003642_1](https://user-images.githubusercontent.com/4204940/31990675-ff2c6da0-b932-11e7-89c2-9e690ae25faf.jpg)

**More feedback / suggestions:**
Radiation effects for lower % of irradiation is a bit harsh for my tastes- the "fuzzy" effect hurts my eyes (personal preference) I got annoyed by it after awhile.  I was not able to find any of the anti-radiation medical items in the loot table.  Found a few First Aid Stations (furniture) but all had FAK's in them.

Could not access a toilet that was located next to a couch - tried everything. Seems that having the furniture so close to each other prevented the cursor target.  Normally the cursor target on the toilet works perfectly

Viewers tonight suggested a "take all" option for all furniture... I am neutral on this personally

All shipwrecks are marked on the map with the new icons but not all have treasure chests- I found 4 out of 10 that had treasure.  No sharks were in the vicinity of the treasure chest that I could find.  The "animal marker" option that DirtySanchez suggested I use was not available in the admin menu that I could find.  Also, the loot from the treasure chests left a bit to be desired.  Loot from cargo containers / satellites is much better and easier to get to.  I vote to remove iron ore from the treasure chest and have all precious metals / gems to make it worth while.

Ferris Wheel loot is working but there isn't a lot of it.  Only 1-2 pieces of furniture spawning when I test it with a group (subjective).

For the radiated towns, there doesn't seem to be an upside to looting the town- all that happens is your character gets irradiated and you need meds to clear it up.  

My idea is to have some incentive to loot the "rad towns"  A military target could be hidden somewhere within the town, it would be a pallet similar to the supply drop and could also have a few pelican cases surrounding it.  The whole town would be radiated but around the "target" there could be higher levels of radiation.  The geiger counter could be a vital item to finding the "target" as you could track the high levels of radiation telling you if you are "hot" or "cold" when looking for it.  The rad towns could be an intense competitive PVP situation for players as well... You could have drones that spawn as soon as the target is found if you wanted to also.  Something to think about anyways, I personally would like to see some incentive to the radiated towns.

**Comment by ravmustang** [comment] 2017-10-24 14:04
Yes the Geiger Counter was chosen to fill the GPS slot as both display in the same area and we have some other plans for the watch slot.

Pipes large and small added to World Interactions here:
https://github.com/EpochModTeam/Epoch/compare/f8a7a569ced6...28042eb84a52

Malden blue garbage cans added here:
https://github.com/EpochModTeam/Epoch/compare/029fa396be35...70df6a8038bd

**Comment by ravmustang** [comment] 2017-10-24 14:23
Underwater shipwrecks on Malden added here:
https://github.com/EpochModTeam/Epoch/compare/04e922d544d5...24d059f0c9b5

**Comment by vbawol** [comment] 2017-10-24 14:26
Fyi, The shipwrecks are controlled by the containerPos array in the map specific server settings.
https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_server_settings/configs/maps/Malden.h#L28 they represent the positions of underwater wrecks.

**Comment by vbawol** [comment] 2017-10-24 14:34
Also, We might be able to do this dynamically based some usage of nearestTerrainObjects.

**Comment by raymix** [comment] 2017-10-24 15:29
> we have some other plans for the watch slot.

@ravmustang Ohhh? Tell me :)

edit: I'll take care of sounds when low energy. Not sure how I even forgot about that part lol...

**Comment by raymix** [comment] 2017-10-24 18:36
@orangesherbet Players are allowed to hide geiger counter, but keep the sounds on (or other way around), it's by design... any combination of 3 - visual, alarm and ticks.
So above 2 issues are for the same problem now fixed.

**Comment by vbawol** [comment] 2017-10-24 19:11
- [x] Just tested a bit and it seems that only one "add wall" option is available on the cinder tower and none on the metal tower. (not an issue)
- [x] cinder tower "floor" seems to be a tad lower than metal tower floor.
![20171024140733_1](https://user-images.githubusercontent.com/3138624/31963105-415a6e16-b8c5-11e7-9496-afca89df06e5.jpg)
- [x] cinder tower ghost preview is very faint.
![20171024135259_1](https://user-images.githubusercontent.com/3138624/31963398-1c6847ee-b8c6-11e7-818a-d2f4302c16b1.jpg)

**Closed as completed** 2017-10-28 15:39 UTC
Labels: bug, prio: High
