### ISSUE TITLE
Dynamic HUD UI visible scrollbars at some aspect ratios

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#654] opened 2016-11-06 15:40 UTC
https://cdn.discordapp.com/attachments/133057507928047616/244558526993661952/107410_screenshots_20161105211939_1.jpg
Moved:
https://cdn.discordapp.com/attachments/133057507928047616/244600934297108480/107410_screenshots_20161106001044_1.jpg

https://cdn.discordapp.com/attachments/133057507928047616/244600934297108480/107410_screenshots_20161106001044_1.jpg

"... The Scrollbar is only there with a resolution of 16:10" @Ignatz-HeMan 

I use 16:10 also and did not see this last I tested. Maybe we can just suppress the scrollbars, but that could result in clipping. 

@raymix any ideas on how to best solve this?

**Comment by Ignatz-HeMan** [comment] 2016-11-06 16:06
I was able to reproduce it on my Client.
I have a 16:9 Screen and changed ingame to a 16:10 resolution (1680x1050) and also set "aspect ratio" to 16:10.
Before Restarting the Game, no Scrollbar. After Restarting, the Scrollbar was there.

**Comment by ReDBaroN1** [comment] 2016-11-06 16:52
I can verify the same. Although to get rid of it I changed interface size to very small but, now can't see chat :)

**Comment by raymix** [comment] 2016-11-06 22:04
Hi guys
There is no direct fix without some crazy math to resize it for all aspect ratios, but debugging such a thing to find and understand variables could take days.
This happens because HUD uses control groups to populate elements within it. Naturally it takes the size of element and multiplies it by count of elements to create size of this group, makes sense, right? But not in Arma engine. There has to be some small decimal value that causes this.

I'll see if there's a way to either remove the scrollbar or replace it's texture with invisible one in configs. Just need to set up my development environment again, it's been a while.

**Comment by raymix** [comment] 2016-11-06 23:21
I can't reproduce the problem. Tried 2x resolutions at 16:10 - 1440x900 and 1680x1050 with all interface scaling options and restarting on every change.
My current monitor - 1080p (16:9)
All tests were done in windowed mode.

EDIT: full screen doesn't reproduce the problem either
I'm gonna try few other variations like mixmatching aspect ratio and resolution tomorrow.

**Comment by raymix** [comment] 2016-11-06 23:35
Guys, those who can reproduce this, could you please provide me with:
1) your native resolution
2) in-game resolution
3) aspect ratio
4) interface size

Or upload your Documents\Arma3\Arma3.cfg to a pastebin so I can look at it.

Thanks

**Comment by Ignatz-HeMan** [comment] 2016-11-06 23:40
Im already in my bed ;)
My Screen is 16:9 - 1920x1080
For reproducing the Problem, I switched Ingame to:
Fullscreen
1680x1050
16:10

**Comment by Ignatz-HeMan** [comment] 2016-11-06 23:41
Interface Size is small, if I remember right

**Comment by raymix** [comment] 2016-11-07 20:30
Ok good news bois, was able to replicate the problem and got it fixed for you, luckily the fix was already in a core game used elsewhere which means you only need to change single variable in mission file. I have a strange feeling that I intended to apply this fix for this issue, don't remember.
I had an old (let me put emphases on word OLD here) 1050p monitor that I tested this with:
Full screen windowed - 16:10 - Interface small - scrollbar on top menu visible
Full screen - 16:10 - interface normal - scrollbar on bottom menu visible

**Fix**:
github\Epoch_public\Sources\epoch_code\gui\scripts\dynamicHUD\ **epoch_dynamicHUD_start.sqf**
Line:30 - change "rscControlsGroup" to "rmx_rscControlsGroup"
Save, recompile and upload.

**Fix 2**:
Get yourself a cheap 1080p monitor, they are selling for pennies atm, brand new ones around 100 bucks, used ones around the cost of this game :)

In all seriousness though, fix is not really a "fix" per say, it's just a lazy patch that makes scrollbars size of 0, effectively hiding them. There might be artefacts, but not something players should notice.

**Comment by Ignatz-HeMan** [comment] 2016-11-07 20:43
Very nice! Thanks for your very fast fix!
Will change it tomorrow and give Feedback.

**Comment by Pmba79** [comment] 2016-11-08 11:45
1) 1680x1050
2) 1680x1050
3) 16:10
4) Small

I'll try the fix, if I can figure out how :p

**Comment by vbawol** [comment] 2016-11-08 16:28
Fix is live on the dev test server, ready for testing 
69.162.70.162:2302 
https://github.com/EpochModTeam/Epoch/commit/1aa39383cc1a292f8bf7919e870db1b35146be61 b640

**Comment by Ignatz-HeMan** [comment] 2016-11-08 17:09
Already added it to our Server and the affected players said, it fixed the problem.
Many thanks!!!

**Comment by raymix** [comment] 2016-11-08 17:10
Glad to hear, closing this then :)

**Closed as completed by raymix** 2016-11-08 17:10 UTC
Labels: bug
