### ISSUE TITLE
Epoch 0.3.5 Safe / Lock Box  / Forum doesnt work. 

### ISSUE THREAD

**Issue by GERDerDennis** [EpochModTeam/Epoch#432] opened 2015-11-29 15:54 UTC
You have a very big Problems with Safe / Lock Box when a weaponholder is nearby. Pls answer to this issue in the Epoch Forum. 
The Forum still doesnt work. No one can write an answer or make a new Thread. 

https://www.youtube.com/watch?v=y3iIiGaZw0Q

**Comment by vbawol** [comment] 2015-11-29 17:41
Thanks for the report I will look into this bug and the forum issue asap.

**Comment by vbawol** [comment] 2015-12-01 04:55
For testing I have this temp fix available here update your server settings pbo with this : https://github.com/EpochModTeam/Epoch/blob/85a25613549e50c9cee37f817c3ebbbca7eeb96f/Server_Install_Pack/@epochhive/addons/a3_epoch_server_settings.pbo?raw=true

Commit: https://github.com/EpochModTeam/Epoch/commit/85a25613549e50c9cee37f817c3ebbbca7eeb96f

This will currently prevent groundweaponholder access within 5m of a locked vehicle or storage device for non Admins and those that use our AH. Ideally the InventoryOpened handler should be expanded to return both containers so we can move towards preventing the cargo option without a bunch of workarounds. Also note: Since 0.3.5 safes and lockboxes now persist the locked/unlocked states.

**Comment by eedijs** [comment] 2015-12-02 01:48
I still can get into safes even more easily now. This glitch works on vehicles too.

**Comment by RC-Robio** [comment] 2015-12-02 19:57
@eedijs Is this your server or one you play on? I ask because maybe they haven't updated the securtiy settings file. Because Awol's temp fix works just fine.

**Comment by MGTDB** [comment] 2015-12-02 21:46
It's my server eedijs plays on and I used the fix Awol posted almost immediately after he posted it

**Comment by RC-Robio** [comment] 2015-12-02 21:48
Is the fix not working for you guys? I've tried to reproduce it but have been unable to.

**Comment by eedijs** [comment] 2015-12-02 21:49
Just tested and confirmed that fix is not working, in fact it is now easier to access it. Before the fix it wouldn't allow me to open inventory near the safe but now it's easy.

**Comment by MGTDB** [comment] 2015-12-02 21:49
Not working for us,

From our GitHub when I changed it

http://s30.postimg.org/eyl0mm7f5/Clipboard01.jpg

**Comment by RC-Robio** [comment] 2015-12-02 21:57
Correct me if I am wrong. Doesn't infistar not even use the security settings pbo? So if you applied the fix it wouldn't matter. And Awol said that it was for Epoch AH only? I know you guys use Chris's AH so thats why I'm asking.

**Comment by MGTDB** [comment] 2015-12-02 21:58
the security settings still work and are applied with infiSTAR running

**Comment by vbawol** [comment] 2015-12-02 22:42
Another build https://github.com/EpochModTeam/Epoch/releases/tag/0.3.5.055

Build 052-055
[Fixed] Typo in server side AH event handler code and repacked a3_server_settings.pbo.
[Fixed] Storage was incorrectly set to set damage to 99% instead of 1% to temp force maintenance option after restart.
[Fixed] Add player objects to remains collector, this should allow for proper corpse cleanup.
[Changed] Disable simulation of locked storage devices. This also prevents removal of items until device is unlocked/re-simulated.

**Comment by eedijs** [comment] 2015-12-03 18:10
Can't take anything out of a locked safe, but still can peek inside.

**Comment by GERDerDennis** [comment] 2015-12-03 18:24
When you unlocked it is it back in your Inventory.

**Comment by eedijs** [comment] 2015-12-03 18:34
What do you mean? What is back in my inventory?

**Comment by GERDerDennis** [comment] 2015-12-03 18:37
Pack some items in the locked safe. The items will removed from your inventory. When you now open the safe the items are back in your inventory

**Comment by eedijs** [comment] 2015-12-03 18:38
Didn't happen to me. When I try putting something in, nothing happens, but when I try to take a multi gun and then unlock the safe - the multi gun will be in my inventory.

**Comment by KS-Epoch** [comment] 2015-12-10 15:13
it is still possible to take items out of locked safes-u cant take to your inventory but can drop on ground and then take

**Comment by vbawol** [comment] 2015-12-16 17:58
https://github.com/EpochModTeam/Epoch/issues/440

**Comment by eedijs** [comment] 2015-12-19 17:38
The problem we had accessing the safe we're aiming at seems to be fixed - don't have to run around to find the "right" spot to get the inventory of THAT safe. Thanks!

**Closed** 2016-01-08 22:54 UTC
Labels: bug, prio: High
