### ISSUE TITLE
Dynamic Simulation may be a problem with Epoch vehicle spawns

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#831] opened 2017-08-25 19:55 UTC
I have seen and players have additionally reported a problem with new vehicle *spawns* that I think is related to dynamic simulation. Sometimes, when you approach a vehicle that has been spawned at the previous restart it will for no reason, explode. I think that this is happening when the vehicle is placed on the map at that time but allowdamage is not false...?

This has happened many times now on my experimental server... does not affect every vehicle but does affect some.

Cheers,
Grahame.

**Comment by Ignatz-HeMan** [comment] 2017-08-25 19:57
Do they explode directly on spawn or when player comes near / login?

**Comment by Ignatz-HeMan** [comment] 2017-08-25 20:07
Ah okay... Just read "when you approach".
I have already tested a lot with "exploding Vehicles".
I will try to create a workaround. It will be never 100% safe, but much better, I think.

**Comment by morgoth0** [comment] 2017-08-25 20:29
Yes, it is when ARMA puts them on the map as you get near.

Cheers,
Grahame.

**Comment by Ignatz-HeMan** [comment] 2017-08-26 15:11
Also Vehicles parked in Bases or only complete new spawned Vehicles?

**Comment by morgoth0** [comment] 2017-08-26 15:58
On experimental server players have few bases due to the incredibly low loot and no traders so not sure on the vehicles parked in bases. So I can only comment on the newly spawned vehicles tbh

**Comment by Ignatz-HeMan** [comment] 2017-09-03 14:21
The code has changed, that the damage is overall higher then before the update.
Now, the problem is, that "HitHull" is also mostly higher and a "HitHull" > ~0.9 cause the exploding Vehicles on simulation.
This should fix it:
https://github.com/EpochModTeam/Epoch/pull/845/files

**Comment by vbawol** [comment] 2017-09-03 15:04
This should be fixed per #845 by @Ignatz-HeMan

**Closed as completed by vbawol** 2017-09-03 15:04 UTC
Labels: bug, Arma (RV Engine)
