### ISSUE TITLE
High blood pressure caused death will cause another if revived

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#388] opened 2015-09-21 22:57 UTC
If I get killed by a snake or a cultist because of a high blood pressure - I will die instantly after being revived with a multi gun.

**Comment by vbawol** [comment] 2015-10-31 16:57
This is partially by design, for example if you are toxic you should stay that way even if revived. Then we can add more ways to treat the player. Otherwise the revive would be a way to simply reset all your ailments.

In this case we should reset the blood pressure to default so you can have some time to treat your self, or eat/drink.

**Comment by vbawol** [comment] 2016-01-19 19:34
this should be fixed for 0.3.7 as we now reset your blood pressure to 120 on revive. This should allow time for the player to address the reason they are having blood pressure issues.

**Closed by vbawol** 2016-01-19 19:34 UTC
Labels: bug, enhancement, prio: High
