### ISSUE TITLE
Unable to pay for base - no option

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#422] opened 2015-11-23 22:00 UTC
Interaction menu only had "Examine" and it doesn't show the icon like before to pay for the base.

**Comment by RC-Robio** [comment] 2015-11-24 13:34
Press 1 then Hold down spacebar.
![2015-11-24_00001](https://cloud.githubusercontent.com/assets/6058597/11368174/d43e2972-927d-11e5-8117-dc343be5eda8.jpg)

**Comment by eedijs** [comment] 2015-11-24 13:37
What server are you playing on? I'm playing on MGT and it was fixed by the admin - not sure if it was server's fault or epoch update.

**Comment by RC-Robio** [comment] 2015-11-24 13:40
My test server, Only mods are statusbar. With a fresh install. It seems infistar are blocking some dialogs. I don't use infistar but I know MGT does. Please report issues to MGT like these.

**Comment by MGTDB** [comment] 2015-11-24 13:45
We whitelisted the new idd's for those and are working fine

**Comment by MGTDB** [comment] 2015-11-24 13:48
Would of been nice for new idd's to be listed for server owners

So far we have found 1200,-1300,-3000

**Comment by vbawol** [comment] 2015-11-24 15:39
not reproducible, closing issue due to notes above about it being a 3rd party issue

**Closed by vbawol** 2015-11-24 15:39 UTC
