### ISSUE TITLE
0.3.0.3 b4 No cultist spawning + antagonist feedback (update)

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#263] opened 2015-04-12 20:28 UTC
It seems since 0.3.0.1 and this patch, no Cultist have been spawning. Server is 82ndAB, we have had various adjustments tot he night time length to see if that helps but it just seems cultists are not spawning at all.

**Comment by Tigah** [comment] 2015-05-12 02:34
Still no cultist spawning, Sapper spawn rate has decreased considerably and Drones are spawning way too much now. Sometimes 2-3 at a time. AI spawn from drones and follow tracking from drones until drones are taken down. This is good but need it toned down a bit a I believe.

**Comment by DarthRogue** [comment] 2015-05-12 02:37
Yes and the init.sqf line addon for antagonists spawn limit does nothing.  I have drones set to 1 and I still had a report of a single player having 6 drones following him.  The init setting should have limited it to 1 on the server at a time, but it's clearly not working as intended.  

//Spawn Limits
/*Max Server AI Limits 
1. Epoch_Cloak_F = Cultist
2. GreatWhite_F = Great White Shark
3. Epoch_Sapper_F = Regular Sapper
4. Epoch_SapperB_F = Super Sapper (dark)
5. I_UAV_01_F = UAV (that spawns the AI)
6. PHANTOM = Invisible phantom 
7. B_Heli_Transport_01_F = Transport helicopter for the mission system*/
EPOCH_spawnLimits = [2, 1, 5, 5, 3, 2, 1];

**Comment by vbawol** [comment] 2015-07-11 14:43
This should be resolved with the current experimental build

**Closed by vbawol** 2015-07-11 14:43 UTC
