### ISSUE TITLE
[Bug] Bornholm vehicles stacking.

### ISSUE THREAD

**Issue by RC-Robio** [EpochModTeam/Epoch#236] opened 2015-03-20 00:08 UTC
Testing the the latest 0.3.0.1b5
Vehicles are spawning stacked in the airfields.
http://imgur.com/a/E7Beg#0

**Comment by DarthRogue** [comment] 2015-03-24 18:49
I have code for a vehicle fix for Bornholm.  Also works for Taviana as well.  If the devs want it I'll be happy to share, although they will probably come up with their own solution.

**Comment by Skaronator** [comment] 2015-03-24 21:18
Could you post your solution/changes? Some maps doesn't works good with our settings so we are probably moving those settings to server config

**Comment by DarthRogue** [comment] 2015-03-24 21:44
This is the current fix I have.  Seems to work well.  This should work on any map if you only change the coords in the fn_init file.

count ([10058.347,9015.848] nearObjects ["building",25000]);

         ^^^^Center pos                                        ^^^^World Size

https://www.dropbox.com/s/n5r3hw42ucx8jp5/a3_epoch_fixBornholm.pbo?dl=0

**Comment by splitx0** [comment] 2015-03-24 22:00
almost the same for taviana

**Comment by Skaronator** [comment] 2015-03-24 22:12
@DarthRogue Thats code from a old epoch build, please check if its not already fixed with new spawn logic, which spawn the vehicles in citys.

**Comment by DarthRogue** [comment] 2015-03-24 22:15
As of the build I have currently that's floating around in the wild, no, they don't spawn properly on Bornholm.  Can't speak for other maps because I haven't tried them.  But from my experience as of the last couple days, using the default files causes land vehicles to all spawn at airports on Bornholm.  Air and sea vehicles spawn where they should just fine however.

**Comment by Skaronator** [comment] 2015-03-24 22:23
Mh sounds like Bornholm doesn't have a proper config for the city's.

This is the code how we get the Citys:
```
_allCitys = (configfile >> "CfgWorlds" >> worldName >> "Names") call BIS_fnc_returnChildren;
_selectedCity = _allCitys select (floor random (count _allCitys));
_citytyp = getText(_selectedCity >> "type");
```
Our configs allow this "city types":
`["FlatAreaCity","FlatAreaCitySmall","NameCity","NameVillage","NameCityCapital","Airport"]`

I think Bornholm has different names for the types or this config part just not exist. You could check the Bornholm config when you want, I've wiped my PC so don't have the mods and dev tools yet.

**Comment by DarthRogue** [comment] 2015-03-24 22:29
Ahhh....well there we go.  Bornholm uses "NameLocal" for most towns.

**Comment by Skaronator** [comment] 2015-03-24 22:33
Could you check if there are other names as well? and checkout the city size, we have different number of vehicle for each city type.

```
_spawnPositionSize = [
	["FlatAreaCity",1],
	["FlatAreaCitySmall",1],
	["NameCity",2],
	["NameVillage",1],
	["NameCityCapital",4],
	["Airport",5]
];
```
`["name",number of veh.]`
When the limit has been reached, are we increasing the it by the value of 1 (for the whole config)

**Comment by DarthRogue** [comment] 2015-03-24 23:17
I'd do this:

_spawnPositionSize = [
    ["FlatAreaCity",1],
    ["FlatAreaCitySmall",1],
    ["NameCity",2],
    ["NameVillage",1],
    ["NameCityCapital",4],
    ["Airport",5],
    //Bornholm
    ["NameLocal",2],
    ["StrongpointArea",1],
    ["VegetationBroadleaf",1],
    ["VegetationFir",1],
    ["ViewPoint",1]
];

Bornholm also features some of the existing ones, such as FlatAreaCity, NameCityCapital, and Airport, so I don't know if you might want to drop those three on the bottom of the list, as they're mostly wilderness areas with a few barns and cottages sprinkled in here and there.  But they're definitely not what I would call any kind of city or village.

**Comment by Skaronator** [comment] 2015-03-25 10:36
Okay will be fixed with the next build, thanks @DarthRogue

**Comment by DarthRogue** [comment] 2015-03-28 17:30
This is not fixed in 0.3.0.1.  EPOCH_spawn_vehicles.sqf array still shows

_spawnPositionSize=[["FlatAreaCity",1],["FlatAreaCitySmall",1],["NameCity",2],["NameVillage",1],["NameCityCapital",4],["Airport",5]];

Should be:

_spawnPositionSize=[["FlatAreaCity",1],["FlatAreaCitySmall",1],["NameCity",2],["NameVillage",1],["NameCityCapital",4],["Airport",5],["NameLocal",2],["StrongpointArea",1],["VegetationBroadleaf",1],["VegetationFir",1],["ViewPoint",1]];

I updated the "fix" PBO with the correct array and vehicle spawning for land vehicles works as it should.  Please update this for next release.

Thanks!

**Comment by Skaronator** [comment] 2015-03-28 17:39
It will be added a line later. `if (worldName in ["Bornholm"]) then {`

**Comment by moosemilker** [comment] 2015-04-03 06:33
Has this been fixed yet?  I have a Bornholm server and there are around 25 vehicles total.  No new vehicles seem to be spawning in.  These must be the only ones left over that have not exploded.  Server at: 76.22.29.76:2312

**Comment by DarthRogue** [comment] 2015-04-03 14:41
Send me a PM on the Epoch forums and I'll send you a temporary fix until they get the correct code into a public release.

**Comment by Skaronator** [comment] 2015-04-03 14:57
the correct code is in build 13 and higher
![](http://stuff.skaronator.com/20150403145530749.png)

**Comment by moosemilker** [comment] 2015-04-03 16:34
Thanks, Skaronator.

Is it tested / verified fixed?  I run 4 Epoch servers: Altis, Chernarus, Panthera (had to add my own support for Panthera via necessary edits to a3_epoch_server_settings.pbo), and Bornholm.

  - Altis, Chernarus, and Panthera spawn in around 150 vehicles
  - Bornholm has around 25 vehicles (like I said in the post last night)

**Comment by DarthRogue** [comment] 2015-04-03 16:59
In my experience with the stock files as of the build 17 (and now 19) release, air and sea vehicles spawn fine.  Land vehicles do not spawn very many, if at all.  I'm using the same fix PBO as before except I added the town definitions I defined above and it works.  So there must be some difference in the code somewhere.  I'll compare them tonight when I get home from work and see if we can nail down the cause.

Skaronator, is there anywhere else where there's code regarding vehicle spawning?  Or is it just in EPOCH_Spawn_Vehicle.sqf?

**Comment by Skaronator** [comment] 2015-04-03 17:13
> Is it tested / verified fixed?

I didn't have tested it since the game runs like shit after I upgrade my graphicscard for 600$. I just added the fix @DarthRogue told me.

> Skaronator, is there anywhere else where there's code regarding vehicle spawning? Or is it just in EPOCH_Spawn_Vehicle.sqf?

The whole vehicle spawn magic happen in the EPOCH_Spawn_Vehicle.sqf

**Comment by DarthRogue** [comment] 2015-04-03 17:37
I wiped the database on my test server and used the fix PBO.  Vehicles spawned in game according to the database = 162, including land, sea and air vehicles.

Wiped my test server database again and tried loading vehicles with the stock files without the fix PBO.  Vehicles spawned in game according to the database = 159, including land, sea and air vehicles.

So it looks like the stock files are actually working as intended.   I'm at work right now so I can't verify this with my own eyes in game, but according to the db the vehicle spawning is working correctly.  I'll follow up with a visual check later today.  I know I tried the stock files in server build 17 and it was only spawning air and sea vehicles in game.  According to the compare plugin for Notepad++ the EPOCH_spawn_vehicles.sqf file is the same between build 17 and build 19, so I don't know where the change in function could have come from.

**Comment by moosemilker** [comment] 2015-04-03 18:56
I just ran some Bornholm / tests...
  - Blank DB / DarthRogue's Bornholm fix listed above / Epoch Server Build 19: 152 vehicles loaded once the client loaded into the game
  - Blank DB / Stock Epoch Server Build 19: 150 vehicles loaded once the client loaded into the game
  - Deleted the fragmented 17 vehicles from my regular DB / Stock Epoch Server Build 19: 0 vehicles spawned once the client loaded into the game


I checked my RPT file on the last test and this is listed, implying vehicles spawned:
11:45:23 "Epoch: Spawning NPC traders"
11:45:23 "Epoch: Loading vehicles"
11:45:23 "VEH SPAWN TIMER 0.263"
11:45:23 "Epoch: Spawning vehicles"
11:45:23 "Epoch: Loading storage"


My vehicle list state before I wiped it:
  - Vehicle:US777:101  ["O_Truck_03_covered_EPOCH",[[9140,11617.5,-0.015625],[-0.994376,0.0461889,0.0953084],[0.0854683,-0.181498,0.97967]],0,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],0.967895,[[["H_90_EPOCH","","",""],["SMG_02_F","","",""],["hgun_Rook40_snds_F","muzzle_snds_L","",""]],[["jerrycan_epoch","SmokeShellYellow","ItemCoolerE","RabbitCarcass_EPOCH","SatchelCharge_Remote_Mag"],[1,1,1,1,1]],[[],[]],[["muzzle_snds_L","ItemMap"],[1,1]]],[],0]

  - Vehicle:US777:110  ["O_Truck_02_covered_EPOCH",[[9791.5,5784.58,-0.00494385],[-0.206482,0.97845,0],[0,0,1]],0.819691,[0.663638,0.663638,0.663638,1,1,1,0.663638,1,1,1,0.663638,1,1,1,1,0.663638,0.663638,0.663638,0.663638],1,[[["arifle_SDAR_F","","",""]],[["30Rnd_65x39_caseless_mag","20Rnd_556x45_UW_mag","20Rnd_556x45_UW_mag"],[30,20,20]],[[],[]],[["ItemCompass","ItemGPS"],[1,1]]],[],0]

  - Vehicle:US777:134  ["C_SUV_01_EPOCH",[[5985.37,12134.1,0.0125275],[0.764317,-0.644841,0],[0,0,1]],0.787794,[1,1,1,1,1,0.61831,1,1,1,1,1,1,0.0504615,0.0504615,0.0504615,0.0504615,0.0504615,0.0504615,1],1,[[["Binocular","","",""]],[["10Rnd_762x51_Mag","ItemScraps"],[10,1]],[[],[]],[["acc_flashlight"],[1]]],[],0]

  - Vehicle:US777:149  ["C_Hatchback_01_EPOCH",[[3069.6,5501.48,0.0352345],[0.887999,-0.459844,-0.00137617],[0.0103755,0.0170438,0.999801]],0,[0.0110833,0.0169988,0,0.0148349,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],0.992908,[[["hgun_Rook40_F","","",""],["hgun_Rook40_F","","",""]],[["6Rnd_GreenSignal_F","SmokeShellYellow","200Rnd_65x39_cased_Box","SmokeShellPurple","6Rnd_GreenSignal_F","30Rnd_65x39_caseless_mag","20Rnd_762x51_Mag","30Rnd_556x45_Stanag_Tracer_Green","11Rnd_45ACP_Mag","30Rnd_556x45_Stanag_Tracer_Yellow","jerrycan_epoch","16Rnd_9x21_Mag","16Rnd_9x21_Mag","ItemDocument","30Rnd_556x45_Stanag_Tracer_Red","9rnd_45X88_magazine","9rnd_45X88_magazine","JackKit","16Rnd_9x21_Mag"],[6,1,200,1,6,30,20,30,11,30,1,16,16,1,30,9,9,1,16]],[[],[]],[["H_100_EPOCH"],[1]]],[],0]

  - Vehicle:US777:150  ["C_Offroad_01_EPOCH",[[9460.41,11737.5,-0.0294189],[-0.272705,-0.962046,0.0100098],[-0.217131,0.0716777,0.973507]],0.30315,[0.346457,0.30315,0.30315,0.30315,0.30315,0.30315,0.401575,0.30315,0.318898,0.30315,0.30315,0.30315,0.30315,0.30315,0.30315,0.30315,0.30315,0.30315,0.30315],0.988035,[[],[[],[]],[[],[]],[[],[]]],[],5]

  - Vehicle:US777:18  ["C_Offroad_01_EPOCH",[[14659.1,10706.6,-0.0512238],[0.156596,0.985128,-0.07071],[-0.00682142,0.0726704,0.997333]],0.061662,[0.545369,0.359752,1,0.661712,0.147007,0.123631,0.0675875,0.550323,0.550323,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811,0.0511811],0.957056,[[],[["6Rnd_45ACP_Cylinder"],[6]],[[],[]],[[],[]]],[],2]

  - Vehicle:US777:30  ["C_SUV_01_EPOCH",[[14558.6,10124.8,1.86454],[0.479716,-0.837284,-0.262354],[-0.324251,0.108671,-0.939709]],0.188976,[0.681102,1,0.527559,1,1,0.188976,0.417323,0.594488,0.34252,0.590551,0.61811,1,0.141732,0.141732,0.141732,0.141732,0.141732,0.141732,0.208661],0.958876,[[["optic_Arco","","",""]],[["10rnd_22X44_magazine","ItemQuartz","HeatPack","JackKit","SmokeShellOrange","CircuitParts","Towelette","HeatPack","3Rnd_SmokeOrange_Grenade_shell","EnergyPack","EnergyPack","ItemLockbox","scam_epoch","Towelette","ItemGarnet","5Rnd_127x108_APDS_Mag","KitWoodStairs","200Rnd_65x39_cased_Box","ItemLockbox","ItemKiloHemp"],[10,1,1,1,1,1,1,1,3,10,10,1,1,1,1,5,1,200,1,1]],[[],[]],[[],[]]],[],2]

  - Vehicle:US777:36  ["C_Hatchback_01_EPOCH",[[2525.32,9446.83,0.131468],[0.845217,-0.525696,0.0961943],[0.00856624,0.1933,0.981103]],0,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],0.869493,[[["m249Tan_EPOCH","","",""],["arifle_TRG20_F","","",""],["hgun_Pistol_heavy_01_F","","",""],["1911_pistol_epoch","","",""]],[["30Rnd_65x39_caseless_mag","30Rnd_65x39_caseless_mag","VehicleRepairLg","KitTiPi","30Rnd_65x39_caseless_mag","MortarBucket"],[21,30,1,1,30,1]],[[],[]],[["muzzle_snds_H","optic_tws","optic_Nightstalker","optic_DMS"],[1,1,1,1]]],[],0]

  - Vehicle:US777:37
  []
  
  - Vehicle:US777:40
  ["C_SUV_01_EPOCH",[[13853.5,10635,1.74161],[-0.563569,-0.778632,-0.275902],[0.161362,0.223796,-0.961186]],0.191166,[1,0.344336,1,0.379703,0.193143,0.553075,0.553075,0.199226,0.383356,0.198265,0.217165,0.181686,0.158442,0.158442,0.158442,0.158442,0.158442,0.158442,0.196456],1,[[],[[],[]],[[],[]],[["muzzle_snds_acp"],[1]]],[],2]
 
 - Vehicle:US777:41
    []
	
  - Vehicle:US777:46  ["C_SUV_01_EPOCH",[[3744.27,5569.7,0.286612],[0.814209,0.416663,-0.404297],[0.307501,0.281181,0.909054]],0.0354331,[1,0.65748,1,0.673228,0.15748,0.685039,0.169291,0.0787402,0.0984252,0.0551181,0.0590551,0.0905512,0,0,0,0,0,0,0.0866142],0.853355,[[["H_17_EPOCH","","",""]],[["APERSMine_Range_Mag","ItemMixOil","honey_epoch","20Rnd_556x45_UW_mag","APERSMine_Range_Mag"],[1,1,1,20,1]],[[],[]],[[],[]]],[],3]
  
  - Vehicle:US777:60  ["jetski_epoch",[[2439.91,7576.35,0.170812],[-0.602295,-0.797895,0.0245972],[-0.140284,0.136127,0.980709]],0.283465,[0.0314961,0.0275591,0,0.0708661],0.992443,[[],[["SmokeShellGreen"],[1]],[[],[]],[["U_C_Driver_1_orange"],[1]]],[],0]
  
  - Vehicle:US777:70  ["C_Hatchback_02_EPOCH",[[2007.61,9889.52,-0.0210609],[-0.428406,0.903584,-0.00238039],[-0.313746,-0.146281,0.938172]],0,[0.224409,0.279528,0.153543,0.185039,0,0,0,0.0511811,0.0629921,0.0433071,0.0590551,0,0,0,0,0,0,0,0],0.965237,[[["arifle_MX_SW_Black_F","","",""]],[["30Rnd_65x39_caseless_mag"],[30]],[[],[]],[[],[]]],[],4]
  
  - Vehicle:US777:94  ["O_Truck_02_transport_EPOCH",[[5560.9,12641,0.036026],[0.960275,0.279054,0],[0,0,1]],0.0795876,[0.0653956,0.0653956,0.0653956,0.0653956,0.251,0.447652,0.0653956,0.0881396,0.602352,0.602352,0.0653956,0.0653956,0.0653956,0.0653956,0.0653956,0.0653956,0.0653956,0.0653956,0.0653956],1,[[["1911_pistol_epoch","","",""]],[["10Rnd_762x51_Mag","9rnd_45X88_magazine","9rnd_45X88_magazine","ItemCorrugated","7Rnd_408_Mag"],[10,9,9,1,7]],[[],[]],[[],[]]],[],0]
 
 - Vehicle:US777:96  ["C_Hatchback_02_EPOCH",[[9904.59,5652.06,0.0584488],[0.696473,-0.717582,-0.000368283],[0.000483613,-4.38411e-005,1]],1,[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],1,[[],[["6Rnd_GreenSignal_F","30Rnd_9x21_Mag","PaintCanRed"],[6,30,1]],[[],[]],[[],[]]],[],4]

 - Vehicle:US777:97
  []



---
Unless I can find an explicit error, there may be a DB wipe in my server's future...

**Comment by DarthRogue** [comment] 2015-04-03 19:04
Did you wipe the DB when 0.3 was released?

**Comment by moosemilker** [comment] 2015-04-03 19:36
I did not wipe the DB when 0.3 was released.  There were no issues on 3 of my servers, but Bornholm is proving otherwise.

**Comment by moosemilker** [comment] 2015-04-03 22:26
By using this tool, "https://github.com/caoxinyu/RedisClient", I was able to export user specific content from 1 database and import that same content to the new database where vehicles are spawning in.  

Now i have a server full of vehicles, did not have to do a server wipe, and I am hoping the Epoch Server Stock vehicle spawner keeps the vehicle population at a regular quantity.  If this test does not work, I will have to wipe the server.

Thanks for your time, gents.  Have a good one guys.

Skaronator, you can probably close this issue again.

**Comment by Skaronator** [comment] 2015-04-03 22:52
alright have a nice day

**Closed by Skaronator** 2015-04-03 22:52 UTC
Labels: bug, prio: Low
