### ISSUE TITLE
0.3.1.0 bugs

### ISSUE THREAD

**Issue by rc162** [EpochModTeam/Epoch#345] opened 2015-08-01 15:38 UTC
Boss Sapper does not produce green smoke when killed.
 
Some vehicles still appear to blow up on spawn in.
 
Cinder walls still require 4 cinder blocks.
 
Yellow Pallets giving scrap metal instead of cinder blocks,

**Comment by donkeypunchepoch** [comment] 2015-08-01 17:52
Can't confirm sapper or pallets, However vehicle damaged on restarts yes.

Cinder walls req I ring 4 cinder might be caused by your own custom CfgCrafting file mission side.

**Comment by rc162** [comment] 2015-08-01 18:12
Ok, thanks.

**Comment by rc162** [comment] 2015-08-02 01:41
Removed custom crafting but no change unfortunately.

**Comment by AltisTalesDusk** [comment] 2015-08-02 10:54
I can also confirm - Yellow Pallets giving scrap metal instead of cinder blocks.

One of our players logged in to two vehicles exploding and another reported a floating quad bike on load up. Dropping to the floor luckily didn't case enough damage to explode it though.

**Comment by rc162** [comment] 2015-08-09 19:37
Just an update to confirm it is indeed the the custom crafting causing the cinder block issue I had not removed it properly.

**Comment by vbawol** [comment] 2015-08-13 05:01
closing this bulk issue, please post in similar issues or post one issue per post if you still have issues to report.

**Closed by vbawol** 2015-08-13 05:01 UTC
Labels: bug
