### ISSUE TITLE
Duping Problem - Corpse Inventory

### ISSUE THREAD

**Issue by missjennabee** [EpochModTeam/Epoch#364] opened 2015-08-29 15:17 UTC
- If someone dies and respawns, without leaving the lobby, then return to their corpse, they're able to takes items from the body without the items actually leaving the corpse inventory. Meaning they can take an infinite number of whatever is on their body.
- If they die, disconnect (leave the lobby), and log back in this doesn't happen. Items taken from the corpse are removed from corpse inventory.

**Comment by vbawol** [comment] 2016-03-08 15:04
Closing this as I have not seen any other reports about this and cannot reproduce as of yet.

**Closed by vbawol** 2016-03-08 15:04 UTC
Labels: Arma (RV Engine), bug, Needs Tested, prio: Low
