### ISSUE TITLE
Any uniform I wear others still see me in underwear

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#436] opened 2015-12-02 15:49 UTC
Arma 3 or Epoch bug - I don't know, but if I think I'm safe in that bush wearing a full ghillie - suprise, others see me in blazing white underwear.

**Comment by vbawol** [comment] 2015-12-02 16:02
Whats the classname of the uniform you are wearing?, maybe something with the new patch and our re-classed uniforms.

**Comment by eedijs** [comment] 2015-12-02 16:35
Mostly anything really, like full ghillies. I just died in a journalists uniform but when I came back my body had a full ghillie and the same items I had.

Also sometimes I can't right click or left click drag a uniform or vest into my slot if I'm trying to take it out of a safe - I have to drop it on the ground and then wear it. The new update breaks a lot of things, especially that new weight system.

**Comment by Pmba79** [comment] 2015-12-02 18:53
Alot of these issues could be the latest Arma patch, they are testing a hotfix atm..

**Comment by eedijs** [comment] 2015-12-03 21:41
Something I discovered - if I try to right click a uniform or vest in a safe - nothing will happen, but when I throw it on the ground and then try to wear it - it will work, BUT the uniform will not be visible to others, only to myself. This started after the new 1.54 update.

**Comment by vbawol** [comment] 2015-12-17 17:27
still not able to reproduce this issue, does anyone else also have this issue?

**Comment by eedijs** [comment] 2015-12-17 17:33
I've got an idea why it might be. Sometimes when I take a uniform or a vest from a corpse and put it in a vehicle and later when I right click it to wear it, it will stay there and make a copy of the uniform I have on right now (or vest). Wearing one of the copies might be why OR when you put these copies in a safe, lockbox and maybe even a shelf - you can actually put infinite amount of these copies even if the safe is full - would that screw up the whole safe? Because I have one safe that had these copies and if I would take out any uniform it would still be full and I can't right click to wear straight out of the safe - I have to drop it on the ground and then wear it, but the problem is that only I see the uniform, others don't. I've seen many times that other people run around in underwear.

You can try with the copying thing and safes - if you still can't replicate, then I don't know - I'm just guessing.

**Comment by sirkro** [comment] 2015-12-18 19:59
This seems to happen when I try to pick up uniforms from AI. I tend to put all uniforms in storage and it seems to be okay after relog.

That is how I have seen this bug.

**Comment by eedijs** [comment] 2015-12-21 17:27
Yesterday I recorded my teammate's uniform vanish in front of me - he didn't drop it, it just disappeared. Watch the guy in blue t-shirt - https://youtu.be/PahuO-VkT0M

**Comment by vbawol** [comment] 2016-02-29 16:58
Since we still unable to reproduce this issue, I am going to close this for now.

**Closed by vbawol** 2016-02-29 16:58 UTC
Labels: bug, Needs Tested
