### ISSUE TITLE
not possible to sell backpack that is inside your backpack

### ISSUE THREAD

**Issue by KS-Epoch** [EpochModTeam/Epoch#450] opened 2015-12-17 21:06 UTC
[Bug]v3.5.6.0 Not possible to sell backpacks in version 3.5.6.0

**Comment by vbawol** [comment] 2015-12-17 23:09
Did you make sure the backback was empty? as it will not allow you to sell a backpack with items in it

**Comment by KS-Epoch** [comment] 2016-01-04 20:12
Im testing 0.3.7 now. It's not possible to sell backpack what inside backpack.

**Comment by RC-Robio** [comment] 2016-01-08 18:22
I think he means that you cannot sell items that are in your backpack. Only items in chest rig or uniform inventory.

**Comment by KS-Epoch** [comment] 2016-01-08 18:25
no  i mean cannot sell that backpack that is inside backpack. 
robio also got autoban just now

**Comment by RC-Robio** [comment] 2016-01-08 18:36
Didn't think you could put a backpack in a backpack? And it wasn't me with the autoban. Somebody just used my name.

**Comment by Kakysas666** [comment] 2016-01-29 11:31
You can put backpack inside backpack. True, you can not sell that backpack which is inside of your original backpack. Backpack selling works only from your character and only when that backpack is empty. Not a very big deal in my opinion. Provided with the fact that if you have backpack inside backpack and re-log, that backpack will be gone.

**Comment by Nullimeyer** [comment] 2016-02-01 00:05
The Problem is, that Arma can not identify a backpack inside a backpack.
It's because, a backback is no item, no magazine and no weapon. It is a vehicle!!!
So no script have the chance to identify, if a backpack is inside a backpack.

**Comment by Kakysas666** [comment] 2016-02-06 18:19
Oh didn't know that. Haha just arma things.

**Comment by vbawol** [comment] 2016-03-08 15:03
Going to close this for now, but will keep this in mind should a new command get added that allows for this and I am moving towards a packing/unpacking system for backpacks.

**Closed by vbawol** 2016-03-08 15:03 UTC
Labels: bug, prio: Medium
